### PR TITLE
Discussion staging area for the IOR testing branch

### PR DESCRIPTION
**Pull request by JulianKunkel**

### CODE REVIEW

**Comment by gflofst** [comment]
io500.sh line 109 seems to have an error. io500_workdir when it was removed elsewhere. Why remove the prefix?

**Comment by JulianKunkel** [comment]
@gflofst you can make inline comments to the code, that is easier visible.
I made the change cause I made a couple of times minor mistakes typing it.
$io500_workdir is harder to spot.

The setup() function now takes an argument and assigns it to the local variable workdir.
That makes it clear to users how the variable is called and modularizes the script code better.

**Comment by gflofst** [comment]
That is more clear when I look at the file itself. The diff is hard to read. I haven't run it, but reading it seems like it is fine.

**Review by gflofst — APPROVED** [review]

**Review by gmarkomanolis — APPROVED** [review]

**Review by gflofst — APPROVED** [review]
So 4711 is still a thing in Germany? I remember that as the random number of choice in 1995.

**Review by gflofst — APPROVED** [review]

**Review by gflofst — APPROVED** [review]

**Review by gflofst — APPROVED** [review]

**Review by gflofst — APPROVED** [review]

**Comment by adilger** [comment]
I was able to run a full test on my local system in "normal" mode, but hit an error when I added `--mode=extended` to the command line:

    [RESULT]                 find       51.540760 kIOPS : time 24.522 seconds
    --------------------------------------------------------------------------
    MPI_ABORT was invoked on rank 1 in communicator MPI_COMM_WORLD with errorcode -1.

    NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
    You may or may not see output from other processes, depending on
    exactly when Open MPI kills them.
    --------------------------------------------------------------------------
    ERROR: a StoneWallingStatusFile is only sensible when splitting write/read into
    multiple executions of ior, please use -k, (ior.c:1446)

**Review by adilger — APPROVED** [review]

**Review by seattleplus — APPROVED** [review]

**Pull request merged**
